export const RETRIEVE_ALL_ENTRIES = "RETRIEVE_ALL_ENTRIES";
export const RETRIEVE_ENTRY = "RETRIEVE_ENTRY";
export const ADD_UPDATE_ENTRY = "ADD_UPDATE_ENTRY";
export const REMOVE_ENTRY = "REMOVE_ENTRY";
